name: CIFuzz
on: [pull_request]
permissions:
  contents: read
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
      with:
        egress-policy: audit

    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@5024e8764dc450cd709662afaf569315a4c557e2
      with:
        oss-fuzz-project-name: 'msquic'
        dry-run: false
        language: c
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@5024e8764dc450cd709662afaf569315a4c557e2
      with:
        oss-fuzz-project-name: 'msquic'
        fuzz-seconds: 300
        dry-run: false
        language: c
    - name: Upload Crash
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
